image: tstrohmeier/awscli:3.8.3
options:
  docker: true

pipelines:
  default:
    # - step:
    #     script:
    #       - echo $BITBUCKET_BRANCH
    #     - step:
    #         name: Code linting
    #         script:
    #           - npm install eslint
    #           - npx eslint .
    #         caches:
    #           - node
    - step:
        script:
            - eval $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
            - docker build -t je-ifw .
            - docker tag je-ifw:latest 603825719481.dkr.ecr.eu-west-1.amazonaws.com/je-ifw:latest
            - docker push 603825719481.dkr.ecr.eu-west-1.amazonaws.com/je-ifw:latest
