image: node:16

pipelines:
  default:
    - parallel:
        - step:
            name: Code linting
            script:
              - npm install eslint
              - npx eslint .
            caches:
              - node

        - step:
            name: Docker Build/Push
            script:
              - docker build -t je-ifw:$BITBUCKET_BRANCH .
              - docker push 603825719481.dkr.ecr.eu-west-1.amazonaws.com/je-ifw:latest
            services:
              - docker
