image: tstrohmeier/awscli:3.8.3
options:
  docker: true

pipelines:
  default:
    # - step:
    #     script:
    #       - echo $BITBUCKET_BRANCH
    #     - step:
    #         name: Code linting
    #         script:
    #           - npm install eslint
    #           - npx eslint .
    #         caches:
    #           - node
    - step:
        script:
            # aws login
            - eval $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
            # docker
            - export BUILD_ID=$BITBUCKET_BRANCH_$BITBUCKET_COMMIT_$BITBUCKET_BUILD_NUMBER
            - docker build -t $AWS_REGISTRY_URL:$BUILD_ID .
            - docker push $AWS_REGISTRY_URL:$BUILD_ID
            - docker tag ${AWS_REGISTRY_URL}:${BUILD_ID} ${AWS_REGISTRY_URL}:development
            - docker push ${AWS_REGISTRY_URL}:development
