image: tstrohmeier/awscli:3.8.3
options:
  docker: true

pipelines:
  branches:
    dev:
      - step:
          script:
            - IMAGE="603825719481.dkr.ecr.eu-west-1.amazonaws.com/je-ifw"
            - TAG=${BITBUCKET_BRANCH:-$BITBUCKET_TAG}
            - aws configure set aws_access_key_id "${AWS_KEY}"
            - aws configure set aws_secret_access_key "${AWS_SECRET}"
            - eval $(aws ecr get-login --no-include-email --region ap-southeast-1 | sed 's;https://;;g')
            - docker build -t $IMAGE:$TAG .
            - docker push $IMAGE:$TAG

    # - step:
    #     script:
    #       - echo $BITBUCKET_BRANCH
    #     - step:
    #         name: Code linting
    #         script:
    #           - npm install eslint
    #           - npx eslint .
    #         caches:
    #           - node
      