image: tstrohmeier/awscli:3.8.3
options:
  docker: true

pipelines:
  branches:
    dev:
      - step:
          script:
              - aws configure set AWS_ACCESS_KEY_ID ASIAYZFWRJC45AE7KJ6E
              - aws configure set AWS_SECRET_ACCESS_KEY b93f9vj3o+/quMoOLc/iGW4GMs018fd1UWwsr9BI
              - aws configure set region eu-west-1
              - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 603825719481.dkr.ecr.eu-west-1.amazonaws.com
              - docker build -t je-ifw .
              - docker tag je-ifw:latest 603825719481.dkr.ecr.eu-west-1.amazonaws.com/je-ifw:latest
              - docker push 603825719481.dkr.ecr.eu-west-1.amazonaws.com/je-ifw:latest

    # - step:
    #     script:
    #       - echo $BITBUCKET_BRANCH
    #     - step:
    #         name: Code linting
    #         script:
    #           - npm install eslint
    #           - npx eslint .
    #         caches:
    #           - node
      